/** Nové fotky z července 2026 (původně DSC*.jpg). */
export const NEW_GALLERY_FILES = new Set([
  "ai-skoleni-workshop-05.webp",
  "ai-skoleni-workshop-06.webp",
  "ai-skoleni-workshop-07.webp",
  "ai-skoleni-workshop-08.webp",
  "ai-skoleni-workshop-09.webp",
  "ai-skoleni-ucastnici-04.webp",
  "ai-skoleni-ucastnici-05.webp",
  "ai-skoleni-ucastnici-06.webp",
  "ai-skoleni-diskuze-04.webp",
  "ai-skoleni-diskuze-05.webp",
  "ai-skoleni-diskuze-06.webp",
  "ai-skoleni-diskuze-07.webp",
  "ai-skoleni-notebook-03.webp",
  "ai-skoleni-notebook-04.webp",
  "ai-skoleni-prezentace-04.webp",
  "ai-skoleni-prezentace-05.webp",
  "ai-skoleni-prezentace-06.webp",
  "ai-skoleni-tym-04.webp",
  "ai-skoleni-tym-05.webp",
  "ai-skoleni-skupina-03.webp",
  "ai-skoleni-skupina-04.webp",
  "ai-skoleni-lektor-01.webp",
  "ai-skoleni-lektor-prezentace-01.webp",
]);

/** Popisné alt texty pro všechny fotky v galerii. */
export const GALLERY_ALT_TEXTS: Record<string, string> = {
  "ai-skoleni-workshop-01.webp": "Účastníci firemního AI školení pracují na promptech",
  "ai-skoleni-workshop-02.webp": "Skupinová práce na AI workshopu ve firmě",
  "ai-skoleni-workshop-03.webp": "Praktické cvičení s AI nástroji na školení",
  "ai-skoleni-workshop-04.webp": "Lektor vede praktickou část AI školení",
  "ai-skoleni-workshop-05.webp": "Tým pracuje na noteboocích během AI workshopu",
  "ai-skoleni-workshop-06.webp": "Skupina u monitoru řeší úkol na firemním školení",
  "ai-skoleni-workshop-07.webp": "Účastníci AI školení u konferenčního stolu",
  "ai-skoleni-workshop-08.webp": "Praktická část AI kurzu ve firemní místnosti",
  "ai-skoleni-workshop-09.webp": "Interaktivní AI školení s lektorem a účastníky",
  "ai-audit-konzultace-01.webp": "Konzultace v rámci firemního AI auditu",
  "ai-financni-skoleni-01.webp": "Účastníci na kurzu finanční gramotnosti",
  "ai-skoleni-diskuze-01.webp": "Diskuze účastníků během AI školení",
  "ai-skoleni-diskuze-02.webp": "Tým řeší konkrétní zadání na AI školení",
  "ai-skoleni-diskuze-03.webp": "Rozhovor lektora s účastníkem školení",
  "ai-skoleni-diskuze-04.webp": "Účastníci diskutují o AI řešení ve skupině",
  "ai-skoleni-diskuze-05.webp": "Tým sleduje ukázku na notebooku během školení",
  "ai-skoleni-diskuze-06.webp": "Skupinová konzultace u počítače na AI workshopu",
  "ai-skoleni-diskuze-07.webp": "Účastníci společně řeší úkol na monitoru",
  "ai-skoleni-prezentace-01.webp": "Prezentace výstupů z AI školení",
  "ai-skoleni-prezentace-02.webp": "Lektor prezentuje AI nástroje účastníkům",
  "ai-skoleni-prezentace-03.webp": "Shrnutí poznatků na konci AI školení",
  "ai-skoleni-prezentace-04.webp": "Lektor vysvětluje AI nástroje na obrazovce",
  "ai-skoleni-prezentace-05.webp": "Prezentace na velké obrazovce během AI kurzu",
  "ai-skoleni-prezentace-06.webp": "Lektor vede školení s projekcí na TV",
  "ai-skoleni-ucastnici-01.webp": "Účastníci firemního AI školení",
  "ai-skoleni-ucastnici-02.webp": "Tým během praktické části AI kurzu",
  "ai-skoleni-ucastnici-03.webp": "Účastníci sledují ukázku AI nástroje",
  "ai-skoleni-ucastnici-04.webp": "Účastníci soustředěně pracují na AI úkolech",
  "ai-skoleni-ucastnici-05.webp": "Žena s notebookem na firemním AI školení",
  "ai-skoleni-ucastnici-06.webp": "Účastníci AI kurzu v zasedací místnosti",
  "ai-skoleni-notebook-01.webp": "Práce s AI nástrojem na notebooku během školení",
  "ai-skoleni-notebook-02.webp": "Účastník testuje AI nástroj na vlastním úkolu",
  "ai-skoleni-notebook-03.webp": "Notebook s otevřeným AI nástrojem na stole",
  "ai-skoleni-notebook-04.webp": "Praktická práce na laptopu během workshopu",
  "ai-skoleni-tym-01.webp": "Tým na firemním AI školení",
  "ai-skoleni-tym-02.webp": "Skupina účastníků AI hackathonu",
  "ai-skoleni-tym-03.webp": "Týmová práce na projektu během AI školení",
  "ai-skoleni-tym-04.webp": "Tým spolupracuje na AI projektu u stolu",
  "ai-skoleni-tym-05.webp": "Účastníci AI hackathonu v týmové skupině",
  "ai-skoleni-skupina-01.webp": "Skupinová fotografie účastníků AI školení",
  "ai-skoleni-skupina-02.webp": "Účastníci a lektor po skončení školení",
  "ai-skoleni-skupina-03.webp": "Skupinová fotka účastníků po AI workshopu",
  "ai-skoleni-skupina-04.webp": "Tým účastníků firemního AI školení",
  "ai-skoleni-detail-01.webp": "Detail z firemního AI školení",
  "ai-skoleni-lektor-01.webp": "Lektor AIKONIC při firemním školení",
  "ai-skoleni-lektor-prezentace-01.webp": "Lektor prezentuje ChatGPT na obrazovce",
};

export function altForGalleryImage(src: string): string {
  const filename = decodeURIComponent(src.split("/").pop() ?? "");
  return GALLERY_ALT_TEXTS[filename] ?? "Fotografie z firemního AI školení AIKONIC";
}
